var data =[
	{
		gctabTypeDictName: "增删改查表",
		gctabType: 0,
		metadataIdPV: "GCTAB_ID",
		dictTypeCode: "",
		defaultValue: "undefined",
		pkeyCol: "ID",
		gctabIdPV: "c_dev_gctabs",
		pkeyTabPV: "gcmetadatas",
		metadataCd: "GCTAB_ID",
		pkeyGctabId: 2,
		metadataId: 1,
		itIskey: 1,
		gctabId: 0,
		updateUserDictName: "管理员",
		reId: 1,
		gctabCd: "c_dev_gctabs",
		itIslf: 1,
		placeHolder: "业务模型表",
		itIsbean: 1,
		itIsdict: 0,
		itIsaf: 1,
		updateUser: 1,
		dataLock: 0,
		updateTime: "2019-08-27 10:07:46",
		sort: 1,
		itIspkey: 0,
		itIsuf: 1,
		itIsdatafill: 1,
		itIsqf: 1,
		pkeyGctabIdPV: "c_dev_gcmetadatas",
		itIsextra: 1,
		pkeyTab: "gcmetadatas",
		pkeyDfReturn: "",
	},
	{
		gctabTypeDictName: "流程步骤视图",
		gctabType: 1,
		metadataIdPV: "GCTAB_CD",
		dictTypeCode: "",
		pkeyCol: "ID",
		gctabIdPV: "c_dev_gs",
		pkeyTabPV: "systabs",
		metadataCd: "GCTAB_CD",
		pkeyGctabId: 0,
		metadataId: 2,
		itIskey: 0,
		gctabId: 1,
		reId: 2,
		gctabCd: "c_dev_gctabs",
		itIslf: 1,
		placeHolder: "数据表名",
		itIsbean: 1,
		itIsdict: 1,
		itIsaf: 1,
		dataLock: 0,
		updateTime: "2019-08-27 10:07:46",
		sort: 2,
		itIspkey: 1,
		itIsuf: 1,
		itIsdatafill: 1,
		itIsqf: 1,
		pkeyGctabIdPV: "--",
		itIsextra: 0,
		pkeyTab: "systabs",
		pkeyDfReturn: "gctabCd-gctabCd,gctabNa-gctabNa,schemaDb-schemaDb,bizNa-gctabNa,gctabCdPV-gctabCd",
	}
];

var dict=[
	{code: "0", name: "增删改查表"},
	{code: "1", name: "流程步骤视图"},
	{code: "2", name: "自定义查询视图"},
	{code: "3", name: "APP视图"},
]
